try:
    print(x)
except:
    print("Ocurrió una excepción")